### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by alhafidzhamdan** [kircherlab/CADD-SV#1]
Hi there,
Thanks for creating this tool!
I'm trying to use your website form to annotate my SV bed file.
It's not clear how one should structure the format of the input bed file however.
Given a bedpe format file, which coordinate of the pair goes to column 2 and 3?

Here's mine (here i've taken the end2 as column 3).
```
head id_C3N-03182T.bed 
chr2	190386065	190386151	DEL
chr2	190386111	190386105	DEL
chr4	131591037	131591084	DEL
chr4	131591082	131591039	DEL
chr5	38553621	38553674	DEL
chr5	38553658	38553637	DEL
chr5	180507818	180508071	DUP
chr5	180508068	180507821	DUP
chr8	111256766	111256830	DUP
chr8	111256827	111256769	DUP
```

I'm not getting any output whatsoever from the website.

Also am I right in thinking the tool does not include inversion and translocation?
A

**Comment by makirc** [comment]
Hi there, 
Thank you for your message and interest in the software. 

Your input format looks good. If the website is not rejecting an uploaded file than the basic format is correct. Files are parsed before saving on our server for further processing. Must be a problem on our end with the processing. 
I see that you got an empty file back. 
I also see a problem, you are using coordinate ranges that start before they end:
`chr12   68522146        67227031`
Unfortunately, this is currently not correctly handled by our pipeline and the complete file is rejected. I just inserted a check that will switch start and end in the upload. Please reupload your file. Sorry for the inconvenience.
 
You are also correct in that we are not supporting inversions or translocations (we did not have training data for these kinds of events). 

Best,
Martin

**Comment by alhafidzhamdan** [comment]
Hi Martin,
Thanks for getting back and tweaking your code, it seems to work now. 
A
