### ISSUE TITLE
Missing header in output

### ISSUE THREAD

**Issue by Han-Cao** [kircherlab/CADD-SV#10]
Hi,

I found the output drop column name of "CADD-SV raw score", resulting in the incorrect header for columns after phred-score. 

For example:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

chr | start | end | type | name | CADDSV-score | raw-score-span | raw-score-flank | CADD_max | CADD_sum | PhastCons100_max | PhastCons100_sum | PhastCons30_max | PhastCons30_sum | PhastCons20_max | PhastCons20_sum | CADD_count | CCR | E1_poised | E2_repressed | E3_dead | E4_dead | E5_repressed | E6_repressed | E7_weak | E8_gene | E9_gene | E10_gene | E11_gene | E12_distal | E13_distal | E14_distal | E15_weak | E16_tss | E17_proximal | E18_proximal | E19_tss | E20_poised | E21_dead | E22_repressed | E23_weak | E24_distal | E25_distal | nr_ctcf_BS | ctcf_nr_bases | ctcf_fraction | DI_min | DI_max | DNase.seq_max | DNase.seq_sum | H2AFZ_max | H2AFZ_sum | H3K27ac_max | H3K27ac_sum | H3K27me3_max | H3K27me3_sum | H3K36me3_max | H3k36me3_sum | H3K4me1_max | H3K4me1_sum | H3K4me2_max | H3K4me2_sum | H3K4me3_max | H3K4me3_sum | H3K79me2_max | H3K79me2_sum | H3K9ac_max | H3K9ac_sum | H3K9me3_max | H3K9me3_sum | H4K20me1_max | H4k20me1_sum | totalRNA.seq_max | totalRNA.seq_sum | EP_intra | EP_boundary | EP_ext | EP_distance | FIRE_gm12878_max | FIRE_gm12878_min | FIRE_msc_max | FIRE_msc_min | FIRE_mes_max | FIRE_mes_min | FIRE_imr90_max | FIRE_imr90_min | FIRE_h1_max | FIRE_h1_min | perc_gc | exon | transcript | gene | start_codon | stop_codon | X3utr | X5utr | cds | gerp_max | gerp_count | A549_nested_intra | A549_nested_boundary | A549_nested_ext | A549_nested_dist | A549_tad_intra | A549_tad_boundary | A549_tad_ext | A549_tad_dist | caki2_nested_intra | caki2_nested_boundary | caki2_nested_ext | caki2_nested_dist | caki2_tad_intra | caki2_tad_boundary | caki2_tad_ext | caki2_tad_dist | escTAD_intra | escTAD_boundary | escTAD_ext | escTAD_distance | microsyn_intra | miscrosyn_boundary | microsyn_ext | microsyn_distance | MPC | pli | exon_dist | gene_dist | start_codon_dist | remapTF | f5_enhancers | DDD_HaploInsuf | deepC_saliencie | nr_uc_elements | nr_uc_bases | uc_fraction | LINSIGHT |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 85440802 | 85440877 | DEL | test_chr1:85440802-85440877 | 31 | 0.975740902 | 0.532292662 | 0.975740902 | 0.174320632 | 0.303273 | 0.822741 | 0.084122 | 0.8488 | 0.032106 | 0.895259 | 0.060158 | 0.530481 | -0.2139 | -0.33748 | -0.33745 | -0.45738 | -0.05991 | -0.41814 | -0.20909 | -0.46126 | -0.3204 | -0.26107 | -0.21539 | 0.417095 | 0.016964 | 1.325423 | -0.50277 | 0.367497 | -0.17066 | -0.0228 | -0.24288 | -0.22054 | -0.16873 | -0.62871 | -0.34196 | -0.39717 | 0.06043 | 0.051632 | -0.03945 | -0.03863 | -0.11431 | -1.19839 | 0.620707 | -0.20368 | -0.50226 | -0.24892 | -0.32348 | -0.18769 | -0.24996 | -0.2734 | -0.28793 | -0.24038 | -0.24553 | -0.26375 | -0.27039 | -0.18971 | -0.20456 | -0.1624 | -0.18504 | -0.13963 | -0.14453 | -0.15676 | -0.20269 | -0.51219 | -0.53241 | -0.13505 | -0.13807 | -0.0655 | -0.23268 | 2.144238 | -1.93954 | -0.17975 | -1.33003 | 3.74549 | 3.843992 | -0.22831 | -0.22929 | -0.16531 | -0.16611 | -0.23986 | -0.24024 | -0.16786 | -0.16823 | 0.485743 | -0.46569 | 0.066885 | 0.066885 | -0.04038 | -0.03648 | -0.03951 | -0.03662 | 0.414916 | 1.755174 | 1.032673 | 0.382543 | -0.37654 | -0.05909 | 1.491063 | 0.456313 | -0.43993 | -0.10131 | 0.088538 | 0.357634 | -0.35285 | -0.05164 | 1.415113 | 0.438994 | -0.42199 | -0.10261 | 0.097749 | 0.310279 | -0.29444 | -0.08969 | -0.59891 | -0.1938 | 0.197384 | -0.03608 | -0.64139 | -0.28562 | -0.49435 | 0.3137 | -0.79463 | -0.21424 | -0.21832 | -0.03453 | 1.698594 | -0.16982 | -0.0319 | 0.619747 | 4.451285 | 0.682787

</body>

</html>

Thanks,
Han

**Comment by varunkas** [comment]
I too have this issue...

**Comment by CatonaO** [comment]
Hello,
Thank you for pointing that out, we have now fixed this issue with the header, for this to work effectively please download the dependencies again, other than just pulling the git repository to update, also remove the run.caddsv environment and create it again from the updated "environment.yaml". 
Best,
Orazio
