### ISSUE TITLE
CADD_SV web-upload failed to score all variants

### ISSUE THREAD

**Issue by jasonbhn** [kircherlab/CADD-SV#2]
Hi, I've uploaded a bed file with 1100 variants. But the returned results contains only 870. I reuploaded the un-scored ones. They came back with score but also have a few not scored. I wonder what's the problem here.

**Comment by makirc** [comment]
Hi Jason, sorry for these unexpected results. @kleinertp is currently out of office. can you send me the job identifiers that you got back (e.g. name of the file that you downloaded) for these two submissions? maybe I can see whether there is some kind of error output. just from the number of SVs that you send, I was unable to directly identify your submissions.

**Comment by makirc** [comment]
I am closing this out. If the problem persists, please reopen or contact us again with the submission IDs or example files so that we can look into that issue.
