### ISSUE TITLE
Bed file must be sorted

### ISSUE THREAD

**Issue by andrewSharo** [kircherlab/CADD-SV#3]
Thanks for developing this method!

I ran CADD-SV locally on a bed file and received the following error
```
Error: Sorted input specified, but the file beds/chrs1357/chrs1357_wchr.bed has the following out of order record
chr7    72576419        72815631
Error: Sorted input specified, but the file beds/chrs1357/chrs1357_wchr.bed has the following out of order record
chr7    72576419        72815631
```

It appears that it requires a sorted bed file. Indeed, using a sorted bed file solved the problem. 

I would recommend mentioning this in the ReadMe file, just because the snakemake output requires a lot of scrolling to get to the original error, which could trip up some folks.

Best, Andrew

**Comment by frequena** [comment]
I completely agree! A mention about it would be very helpful

**Comment by kleinertp** [comment]
Thanks for the hint,

I added this information in the manual
