### ISSUE TITLE
config.yml file format

### ISSUE THREAD

**Issue by bhagesh-h** [kircherlab/CADD-SV#6]
Please add more detailed instructions to update dataset names config.yml file.

**Comment by kleinertp** [comment]
Config yml needs to contain the name of your bedfile without the .bed.
So if you want to analyze a dataset called test.bed, specify this in the config yml by adding "test" to the dataset name.
The format of the yml can be seen in the example config yml provided.

Not sure if this answers your question

**Comment by bhagesh-h** [comment]
Thank you @kleinertp
