### ISSUE TITLE
output bed header

### ISSUE THREAD

**Issue by zihhuafang** [kircherlab/CADD-SV#7]
Hi @kleinertp,

Thanks a lot for developing CADD-SV.
While I was checking the output bed file for CADD-scores, I noticed the number of the header fields (136) did not match the number of the data fields (137).

"raw-score-combined" is present in scoring.R but missing in the annotations/header_final.txt
I checked the column annotations in v1.0 and v1.1 (https://kircherlab.bihealth.org/download/CADD-SV/) and 'raw-score-combined' was not present in either version.

Just want to double check if it's intentional to leave out "raw-score-combine" in the header?
Thanks!

**Comment by kleinertp** [comment]
Hi Zi-Hua Fang,
Thanks for pointing this out. This is not intentional.
I will update the header annotations,

Thank you!
