### ISSUE TITLE
vcf annotation 

### ISSUE THREAD

**Issue by Manuelaio** [kircherlab/CADD-SV#8]
Hi, 
thank you for developing this score for SVs. 
I'm writing to know if it is possibile use this score as VEP plugin for SVS-vcf annotations, do you have any suggestions ? 
Thanks 
manuela

**Comment by kleinertp** [comment]
Hi Manuela,

I dont think this request is an "issue",
I am not familiar with VEP or know how to use CADD-SV as annotation there.
So unfortunately I have no suggestions,

Best

Philip

**Comment by Manuelaio** [comment]
Yes, I know 
I'm closing the issue and thank you for clarifing
