### ISSUE TITLE
Very high CADD score for common SV

### ISSUE THREAD

**Issue by Han-Cao** [kircherlab/CADD-SV#9]
Hi,

Thank you for deveoping this great tool. 

I would like to use CADD-SV in my study. However, I found a few common SV exhibit very high CADD score, one of them is:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>
<body link="#0563C1" vlink="#954F72">

Chrom | Start | End | Type | Name | CADD-SV PHRED-score | CADD-SV Raw-score | Raw-Score span | Raw-Score flank | CADD max | CADD sum
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 85440802 | 85440877 | DEL | Beyter_D_2021_chr1:85440802-85440877 | 31 | 0.97574 | 0.53229 | 0.97574 | 0.17432 | 0.30327
1 | 85440803 | 85440876 | DEL | Abel_HJ_2020_DEL_chr1:85440803-85440876 | 31 | 0.97574 | 0.53566 | 0.97574 | 0.17432 | 0.30327

</body>

</html>

This deletion is quite common, i.e., in gnomAD-SV, AF=0.15 in East Asian (DEL_1_5559). I noticed that this high CADD score is due to flanking region, I did some search on UCSC browser but didn't find key feature can contribute to it.

I manually check some of the "abnormal" common SV and found they are overlapped by some large deleterious SVs. The above example SV is overlapped by:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

Chrom | Start | End | Type | Name | CADD-SV PHRED-score | CADD-SV Raw-score | Raw-Score span | Raw-Score flank | CADD max | CADD sum
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 84762783 | 85491963 | DEL | gnomAD_DEL_chr1:84762783-85491963 | 36 | 0.98761 | 0.98761 | 0.1672 | 3.32471 | 3.66879

</body>

</html>

Could you give some advice on it?

Thanks,
Han

**Comment by kleinertp** [comment]
Hi Han,

I think would you did is the correct way to use CADD-SV Scores.
It is an estimate of pathogenicity. As CADD-SV uses neither allelefrequency nor labelled pathogenic variants, this is a great way to confirm the validity of the score. Also keep in mind that high scores could still be functional even though they are not pathogenic
